name: plantcare
description: "App Flutter per la gestione e il monitoraggio della propria collezione di piante."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.7
  fl_chart: ^0.66.0
  flutter_launcher_icons: ^0.14.0
  # SQLite 
  sqflite: ^2.3.0
  path: ^1.8.3
  # SQLite FFI desktop 
  sqflite_common_ffi: ^2.3.2

  flutter_heatmap_calendar: ^1.0.5
  intl: ^0.19.0 # Per formattare le date
  collection: ^1.18.0 # Per la funzione groupBy

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

  intl: ^0.19.0

  flutter_riverpod: ^2.5.1

flutter:

  uses-material-design: true

  assets:
    - assets/icon.png